source 'http://rubygems.org'
gem 'rails', '4.2.8'
gem 'sqlite3', '1.3.13'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'web-console', '~> 2.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bcrypt'
gem 'kaminari', '1.1.1'
gem 'ckeditor', '4.3.0'
gem 'bootstrap-datepicker-rails', '1.8.0.1'
gem 'paperclip', '5.1.0'
gem 'table_print', '1.5.6'
gem 'activerecord-reset-pk-sequence', '0.2.1'
gem 'google-api-client', '~> 0.7.1'
gem 'retriable', '1.4.1'
gem 'prawn', '2.2.2'
gem 'prawn-table', '0.2.2'
gem 'data-confirm-modal', '1.6.2'
gem 'dynamic_form', '1.1.4'
gem 'cocaine'
gem 'jquery-validation-rails'
gem 'active_attr', '0.12.0'
gem 'meta-tags', :require => 'meta_tags'
gem 'truncate_html'
#gem 'nokogiri', '1.6.6.2'
gem 'nokogiri', '1.7.0'
gem 'public_suffix', '3.0.3'
gem 'friendly_id', '~> 5.2.0'
gem 'recaptcha'
group :production do
  gem 'mysql2', '~> 0.3.18'
end
